```{r}
# Load the analysis script
#source("outer_cv_analysis.R")
```

```{r}
clean_probs_str <- function(probs_str) {
  probs_str %>%
    str_replace_all("\\[|\\]|\\{|\\}|\\\n|,", "") %>%  # remove brackets and line breaks
    str_squish() %>%                                 # collapse multiple spaces
    str_split(" ") %>%                               # split by space
    unlist() %>%
    as.numeric()
}

modify_classes <- function(vector){
  vector[grepl("MDS|TP53", vector)] <- "MDS-r"
  vector[!grepl("MLLT3", vector) & grepl("KMT2A", vector)] <- "other KMT2A"
  vector
}
```


```{r}
rgas_path <- "../data/rgas.csv"
y <- read.csv(rgas_path)$ICC_Subtype

studies_path <- "../data/meta.csv"
studies <- read.csv(studies_path)$Studies

atleast_10 <- names(which(table(y) >=10))
exclude <- c("AML NOS", "Missing data")
selected_studies <- c(        
        "TCGA-LAML",
        "LEUCEGENE",
        "BEATAML1.0-COHORT",
        "AAML0531",
        "AAML1031"
        )


y <- y[y %in% atleast_10 & !y %in% exclude & studies %in% selected_studies]
```

```{r}
cms_from_ovr <- function(results_df){
  outer_folds <- unique(results_df$outer_fold)
  
  cm_list <- list()
  for (outer_fold in outer_folds){
    results_df_fold <- results_df[results_df$outer_fold == outer_fold,]
    
    test_indices <- clean_probs_str(results_df_fold$sample_indices[1]) + 1
    n_samples <- length(test_indices)
    prob_df_fold <- data.frame(matrix(nrow = n_samples, ncol = 0))
    
    y_test_fold <- y[test_indices]
    
    classes <- unique(results_df_fold$class_label)
    for (i in 1:nrow(results_df_fold)){
      class <- results_df_fold$class_label[i]
      prob_df_fold[class] <- clean_probs_str(results_df_fold$preds_prob[i])
    }
    
    preds <- colnames(prob_df_fold)[apply(prob_df_fold, 1, which.max)]
    
    y_mod <- modify_classes(y_test_fold)
    preds_mod <- modify_classes(preds)
    
    all_classes <- unique(y_mod)
    y_mod <- factor(y_mod, levels = all_classes)
    preds_mod <- factor(preds_mod, levels = all_classes)
    
    cm_list[[as.character(outer_fold)]] <- caret::confusionMatrix(preds_mod, y_mod)
  }
  return(cm_list)
}
# yay!
cbind.fill<-function(...){
    nm <- list(...) 
    nm<-lapply(nm, as.matrix)
    n <- max(sapply(nm, nrow)) 
    do.call(cbind, lapply(nm, function (x) 
    rbind(x, matrix(, n-nrow(x), ncol(x))))) 
}
mean_overall <- function(cm_list, model, type){
  kappas <- sapply(cm_list, function(x) x$overall["Kappa"])
  mean_kappas <- mean(kappas)
  sd_kappas <- sd(kappas)
  
  acc <- sapply(cm_list, function(x) x$overall["Accuracy"])
  mean_acc <- mean(acc)
  sd_acc <- sd(acc)
  
  return(data.frame(model, type, mean_kappas, sd_kappas, mean_acc, sd_acc))
}

mean_per_class <- function(cm_list, model, type){
  byClass_Balanced.Accuracy <- do.call(cbind.fill,lapply(cm_list, function(x) data.frame(x$byClass)["Balanced.Accuracy"]))
  classes <- rownames(byClass_Balanced.Accuracy)
  mean_Balanced.Accuracy <- apply(byClass_Balanced.Accuracy, 1, mean, na.rm = TRUE)
  sd_Balanced.Accuracy <- apply(byClass_Balanced.Accuracy, 1, sd, na.rm = TRUE)
  
  byClass_F1 <- do.call(cbind.fill,lapply(cm_list, function(x) data.frame(x$byClass)["F1"]))
  mean_F1 <- apply(byClass_F1, 1, mean, na.rm = TRUE)
  sd_F1 <- apply(byClass_F1, 1, sd, na.rm = TRUE)

  byClass_Sensitivity <- do.call(cbind.fill,lapply(cm_list, function(x) data.frame(x$byClass)["Sensitivity"]))
  mean_Sensitivity <- apply(byClass_Sensitivity, 1, mean, na.rm = TRUE)
  sd_Sensitivity <- apply(byClass_Sensitivity, 1, sd, na.rm = TRUE)
  
  byClass_Specificity <- do.call(cbind.fill,lapply(cm_list, function(x) data.frame(x$byClass)["Specificity"]))
  mean_Specificity <- apply(byClass_Specificity, 1, mean, na.rm = TRUE)
  sd_Specificity <- apply(byClass_Specificity, 1, sd, na.rm = TRUE)
  
  data.frame(model, type, "class" = classes, mean_Balanced.Accuracy, sd_Balanced.Accuracy, mean_F1, sd_F1, mean_Sensitivity, sd_Sensitivity, mean_Specificity, sd_Specificity)
}

expand_cm <- function(cm_table, all_levels) {
  # Create a full zero matrix
  full_cm <- matrix(0, nrow = length(all_levels), ncol = length(all_levels),
                    dimnames = list(Reference = all_levels, Prediction = all_levels))
  
  # Fill in the known values
  full_cm[rownames(cm_table), colnames(cm_table)] <- cm_table
  return(full_cm)
}


combine_cms <- function(cms){
  cms_only <- lapply(cms, function(x) x$table)
  all_levels <- sort(unique(unlist(lapply(cms_only, function(x) union(rownames(x), colnames(x))))))
  expanded_cms <- lapply(cms_only, expand_cm, all_levels = all_levels)
  combined_cm <- Reduce(`+`, expanded_cms)
  combined_cm
}

analyse_ovr <- function(file, model, type, y){
  results_df <- read.csv(file)
  
  cms <- cms_from_ovr(results_df)
  
  means_df <- mean_overall(cms, model, type)
  per_class_df <- mean_per_class(cms, model, type)
  combined_cm <- combine_cms(cms)
  
  out <- list(means_df, per_class_df, combined_cm)
  return(out)
}



analyse_all_ovr <- function(to_analyse){
  out <- lapply(to_analyse, function(x){
    analyse_ovr(x[1], x[2], x[3], y)
  })
  overall <- do.call(plyr::rbind.fill, lapply(out, function(x) x[[1]]))
  per_class <- do.call(plyr::rbind.fill, lapply(out, function(x) x[[2]]))
  combined_cm <- lapply(out, function(x) x[[3]])
  
  out <- list(overall, per_class, combined_cm)
  names(out) <- c("overall", "per_class", "cms")
  return(out)
}
```

```{r}
to_analyse <- list(
c("../out/outer_cv/SVM_n10/SVM_outer_cv_CV_OvR_20250703_1254.csv", "SVM", "CV"),
c("../out/outer_cv/SVM_n10/SVM_outer_cv_loso_OvR_20250703_1309.csv", "SVM", "LOSO"),
c("../out/outer_cv/XGBOOST_n10/XGBOOST_outer_cv_CV_OvR_20250703_1259.csv", "XGBOOST", "CV"),
c("../out/outer_cv/XGBOOST_n10/XGBOOST_outer_cv_loso_OvR_20250703_1312.csv", "XGBOOST", "LOSO")
)

out <- analyse_all_ovr(to_analyse)
```


```{r}
out$overall
```
```{r}
library(dplyr)
out$per_class %>% filter(type == "CV") %>% group_by(class) %>% filter(mean_F1 == max(mean_F1))
```

```{r}
out$cms[[2]]
```

```{r}
xgb_results <- run_outer_cv_analysis("XGBOOST", "CV", base_path = "../out/outer_cv/SVM_n10/")

xgb_results$ovr$confusion_matrix$overall
```

```{r}
# Run analysis for SVM  
svm_results <- run_outer_cv_analysis("SVM", "CV")

svm_results$ovr$confusion_matrix$overall

```
```{r}
svm_results$ovr$confusion_matrix$table
```

```{r}
true_values <- as.character(svm_results$ovr$true_values)
preds <- as.character(svm_results$ovr$predictions)

true_values[grepl("KMT2A", true_values) & !grepl("MLLT3", true_values)] <- "Other KMT2A"
preds[grepl("KMT2A", preds) & !grepl("MLLT3", preds)] <- "Other KMT2A"

levels_labels <- unique(true_values, preds)

true_values <- factor(true_values)
preds <- factor(preds)

res <- caret::confusionMatrix(true_values, preds)
res$overall
```

